all: arraylist pointerlist arraystack pointerstack timing pushpoptiming
.PHONY: all
.PHONY: clean

arraylist:
	@python arraylist.py
	echo arraylist is good

pointerlist:
	@python pointerlist.py
	echo pointerlist is good

arraystack:
	@python arraystack.py
	echo arraystack is good

pointerstack:
	@python pointerstack.py
	echo pointerstack is good

timing:
	@python timing.py
	echo timing is good

pushpoptiming:
	@python pushpoptiming.py
	echo timing is good

clean:
	@\rm -f *.pyc
