all: pointerqueue mergelists listconcat levelorder traversalconvert preorder postorder huffman
.PHONY: all
.PHONY: clean

pointerqueue:
	@python pointerqueue.py
	echo pointerqueue is good

mergelists:
	@python mergelists.py
	echo mergelists is good

listconcat:
	@python mergelists.py
	echo mergelists is good

levelorder:
	@python levelorder.py
	echo mergelists is good

traversalconvert:
	@python traversalconvert.py
	echo traversalconvert is good

preorder:
	@python preorder.py
	echo preorder is good

postorder:
	@python postorder.py
	echo postorder is good

huffman:
	@python huffman.py
	echo huffman is good
